name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make
      - name: Copy script
        run: cp tests/script.sh .
      - name: Run tests
        run: |
          for i in 1 2 3 4 5
          do 
            for j in 1 2 3
            do 
              ./script.sh $j
            done
          done
